# Generated by Django 6.0.2 on 2026-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=50)),
                ('a', models.IntegerField(max_length=10)),
                ('c', models.IntegerField(max_length=15)),
                ('e', models.EmailField(max_length=30)),
                ('d', models.CharField(max_length=50)),
            ],
        ),
    ]
