# Generated by Django 6.0.2 on 2026-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='d',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='e',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='n',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='a',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='c',
        ),
        migrations.AddField(
            model_name='emp',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='emp',
            name='contact',
            field=models.IntegerField(default=100),
        ),
    ]
