# Generated by Django 6.0.2 on 2026-02-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_d_emp_department_rename_e_emp_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='department',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='name',
            new_name='n',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='age',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='email',
        ),
        migrations.AddField(
            model_name='emp',
            name='a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='e',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
