# Generated by Django 6.0.2 on 2026-02-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_department_emp_d_rename_name_emp_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit_que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=50)),
                ('e', models.EmailField(max_length=254, null=True)),
                ('c', models.IntegerField()),
                ('d', models.CharField(max_length=50)),
                ('q', models.CharField(max_length=100)),
            ],
        ),
    ]
