# Generated by Django 6.0.2 on 2026-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_submit_que'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_que',
            name='c',
            field=models.CharField(max_length=50),
        ),
    ]
