# Generated by Django 6.0.2 on 2026-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_submit_que_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dep',
            name='d',
            field=models.CharField(max_length=50),
        ),
    ]
